### ISSUE TITLE
Use with CRA without ejecting?

### ISSUE THREAD

**Issue by onpaws** [seek-oss/css-modules-typescript-loader#21]
Hello,
This project looks useful, thanks for making this.

I am required to use [CRA](https://github.com/facebook/create-react-app) on a project & considering ways to add `css-modules-typescript-loader`. CRA [evidently](https://github.com/onpaws/cra-typescript-cssmodules) supports CSS Modules and TypeScript separately, but _not together_. At least, not today.

It's been a little while since I faced this problem of CRA deliberately not supporting custom webpack configs by design. In the absence of any knowledge on 2019 practices, my inclination would be to fork `react-scripts` and add this project as a dep. 
While I can do this, I'm wondering if there might be a cleaner way to handle this?

**Comment by mattsjones** [comment]
Sorry, no way we can support this from our side. The issue is with CRA.

**Comment by fourpastmidnight** [comment]
Use [craco](https://github.com/gsoft-inc/craco)? Follow the directions at craco to set it up for use with your project. Then all you need to do is add the following in the `craco.config.js` file:

```javascript
const { addAfterLoader, loaderByName, throwUnexpectedConfigError } = require('@craco/craco');

const throwError = message =>
  throwUnexpectedConfigError({
    packageName: 'craco',
    githubRepo: 'gsoft-inc/craco',
    message,
    githubIssueQuery: 'webpack'
  });

module.exports = {
  webpack: {
    configure: (webpackConfig) => {
      console.log('Adding css-modules-typescript-loader...');
      const cssModulesTypeScriptLoader = {
        loader: require.resolve('css-modules-typescript-loader')
      };
      const { isAdded } = addAfterLoader(webpackConfig, loaderByName('css-loader'), cssModulesTypeScriptLoader);
      if (!isAdded) {
          throwError('Failed to add the css-modules-typescript-loader!')
      }

      return webpackConfig;
    }
  }
};
```

The only issue I'm currently running into is that I'm using a mono-repo with Yarn and PnP and this module seems to be trying to overwrite *.css.d.ts files in the PnP cache, which are really Zip files and so are read-only, causing an error. I'm trying to understand if there's a way to have this loader exclude those files or restrict what it attempts to create a typings file for.

In my project, I'm using Semantic UI React, and in the main `App.tsx` file, I'm using `import 'semantic-ui-css/semantic.min.css'`. This CSS file is offered as a npm library. And because it's imported, this webpack loader is attempting to create a typings flise for it. I really don't want it to.

First, I'm not doing something like `import semanticUIStyles from 'semantic-ui-css/semantic.min.css'`, where then I could use `semanticUIStyles` in my react components to access discrete style classes. I'm simply importing the CSS file so that CSS styles are applied to the elements.
